projects:
  TsukeMonoIshi:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
      - src/API.ts
    extensions:
      amplify:
        version: 3
        generatedFileName: src/API.ts
        codeGenTarget: typescript
        docsFilePath: src/graphql
        maxDepth: 3
extensions:
  amplify:
    version: 3
